"""
Django settings for SmartStudy project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-56u^lzo($llla!_s3i9wssvu3#$s%_dge7skdain(4yvqy%lk*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",  
    "unfold.contrib.filters", 
    "unfold.contrib.forms",  
    "unfold.contrib.inlines", 
    "unfold.contrib.import_export", 
    "unfold.contrib.guardian",  
    "unfold.contrib.simple_history",  
    "unfold.contrib.location_field",  
    "unfold.contrib.constance",  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'StudyPortal.apps.StudyportalConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SmartStudy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SmartStudy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "SmartStudy Admin",

    "SITE_HEADER": "SmartStudy",

    "SITE_SUBHEADER": "StudyPortal Administration",

    "SITE_DROPDOWN": [
        {
            "icon": "home",
            "title": _("SmartStudy Home"),
            "link": "https://smartstudy.example.com",
        },
    ],

    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("logo-light.svg"),
        "dark": lambda request: static("logo-dark.svg"),
    },

    "SITE_LOGO": {
        "light": lambda request: static("logo-light.svg"),
        "dark": lambda request: static("logo-dark.svg"),
    },

    "SITE_SYMBOL": "menu_book",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/png",
            "href": lambda request: static("favicon.png"),
        },
    ],


    "SHOW_HISTORY": True,

    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": False,
    "ENVIRONMENT": "StudyPortal.dashboard.environment_callback",
    "ENVIRONMENT_TITLE_PREFIX": "StudyPortal.environment_title_prefix_callback",
    "DASHBOARD_CALLBACK": "StudyPortal.dashboard.dashboard_callback",
    "THEME": "light",


    "LOGIN": {
        "image": lambda request: static("images/login-bg.jpg"),
        "redirect_after": lambda request: reverse_lazy("admin:StudyPortal_institution_changelist"),
    },

    "STYLES": [
        lambda request: static("css/style.css"),
    ],
    "SCRIPTS": [
        lambda request: static("js/script.js"),
    ],
    "BORDER_RADIUS": "8px",

    "SIDEBAR": {
        "MENU_ITEMS": [
            {"label": _("Dashboard"),"icon": "heroicons-outline:home", "url": "dashboard/",},
            {"label": "Books Custom Page", "url": "/admin/book/custom/", "icon": "book"},
            {"label": "Participant Books Custom Page", "url": "/admin/participantbook/custom/", "icon": "file"},
            {"label": "Resources Custom Page", "url": "/admin/resource/custom/", "icon": "file"},
            {"label": "Notes Custom Page", "url": "/admin/note/custom/", "icon": "file-text"},
            {"label": "Courses Custom Page", "url": "/admin/course/custom/", "icon": "layers"},
            {"label": "Progress Custom Page", "url": "/admin/progress/custom/", "icon": "bar-chart"},
            {"label": "Assignments Custom Page", "url": "/admin/assignment/custom/", "icon": "edit"},
        ],
        "show_search": True,
        "command_search": False,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Navigation"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                        "badge": "StudyPortal.dashboard.badge_callback",
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Institutions"),
                        "icon": "school",
                        "link": reverse_lazy("admin:StudyPortal_institution_changelist"),
                    },
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:StudyPortal_portaluser_changelist"),
                    },
                    {
                        "title": _("Books"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:StudyPortal_book_changelist"),
                    },
                    {
                        "title": _("Courses"),
                        "icon": "library_books",
                        "link": reverse_lazy("admin:StudyPortal_course_changelist"),
                    },
                    {
                        "title": _("Resources"),
                        "icon": "folder",
                        "link": reverse_lazy("admin:StudyPortal_resource_changelist"),
                    },
                    {
                        "title": _("Notes"),
                        "icon": "note",
                        "link": reverse_lazy("admin:StudyPortal_note_changelist"),
                    },
                    {
                        "title": _("Assignments"),
                        "icon": "assignment",
                        "link": reverse_lazy("admin:StudyPortal_assignment_changelist"),
                    },
                    {
                        "title": _("Progress"),
                        "icon": "bar_chart",
                        "link": reverse_lazy("admin:StudyPortal_progress_changelist"),
                    },
                    {
                        "title": _("User Dashboard"),
                        "icon": "home",
                        "link": "/admin/dashboard/"
                    },
                ],
            },
        ],
    },



    "TABS": [
        {
            "models": [
                "StudyPortal.institution",
                "StudyPortal.participantinstitution",
            ],
            "items": [
                {
                    "title": _("Institution Management"),
                    "link": reverse_lazy("admin:StudyPortal_institution_changelist"),
                    "permission": "StudyPortal.dashboard.permission_callback",
                },
            ],
        },
        {
            "models": [
                "StudyPortal.book",
                "StudyPortal.participantbook",
            ],
            "items": [
                {
                    "title": _("Books & Materials"),
                    "link": reverse_lazy("admin:StudyPortal_book_changelist"),
                    "permission": "StudyPortal.dashboard.permission_callback",
                },
            ],
        },
    ],
    "SITE_DROPDOWN":[
        {
            "icon": "school",
            "title": _("Institutions"),
            "link": reverse_lazy("admin:StudyPortal_institution_changelist"),
        },
        {
            "icon": "people",
            "title": _("Users"),
            "link": reverse_lazy("admin:StudyPortal_portaluser_changelist"),
        },
        {
            "icon": "menu_book",
            "title": _("Books"),
            "link": reverse_lazy("admin:StudyPortal_book_changelist"),
        },
        {
            "icon": "library_books",
            "title": _("Courses"),
            "link": reverse_lazy("admin:StudyPortal_course_changelist"),
        },
        {
            "icon": "folder",
            "title": _("Resources"),
            "link": reverse_lazy("admin:StudyPortal_resource_changelist"),
        },
        {
            "icon": "note",
            "title": _("Notes"),
            "link": reverse_lazy("admin:StudyPortal_note_changelist"),
        },
        {
            "icon": "assignment",
            "title": _("Assignments"),
            "link": reverse_lazy("admin:StudyPortal_assignment_changelist"),
        },
        {
            "icon": "bar_chart",
            "title": _("Progress"),
            "link": reverse_lazy("admin:StudyPortal_progress_changelist"),
        },
        {
            "icon": "home",
            "title": _("SmartStudy Home"),
            "link": "https://smartstudy.example.com",
        },
    ]
}










