import os
from typing import List, Optional

try:
    from openai import OpenAI  # type: ignore
except Exception:  # pragma: no cover
    OpenAI = None  # Fallback when package isn't installed

try:
    import google.generativeai as genai  # type: ignore
except Exception:  # pragma: no cover
    genai = None

from pptx import Presentation  # type: ignore
from pptx.util import Inches, Pt  # type: ignore


def _get_openai_client() -> Optional[object]:
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key or OpenAI is None:
        return None
    return OpenAI(api_key=api_key)

def _gemini_configured() -> bool:
    return bool(os.environ.get("GEMINI_API_KEY") and genai is not None)

def _ensure_gemini():
    if not _gemini_configured():
        return False
    genai.configure(api_key=os.environ["GEMINI_API_KEY"])  # type: ignore
    return True


def get_llm_response(prompt: str, role_hint: str = "student", model: str = "gpt-4o-mini") -> str:
    system_prompt = (
        "You are SmartStudy AI Assistant. Provide concise, actionable help for "
        f"{role_hint} workflows in study/teaching contexts. Use lists and steps."
    )

    provider = (os.environ.get("AI_PROVIDER") or "auto").lower()

    # Choose provider: explicit, or auto -> openai then gemini
    if provider == "openai" or provider == "auto":
        client = _get_openai_client()
        if client is not None:
            try:
                r = client.chat.completions.create(
                    model=model,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": prompt},
                    ],
                    temperature=0.2,
                    max_tokens=600,
                )
                return (r.choices[0].message.content or "").strip()
            except Exception:
                pass
        if provider == "openai":
            return (
                "[AI offline] Set OPENAI_API_KEY or set AI_PROVIDER=gemini with GEMINI_API_KEY.\n\n"
                f"Echoing: {prompt[:500]}"
            )

    if provider == "gemini" or provider == "auto":
        if _ensure_gemini():
            try:
                gemini_model = os.environ.get("GEMINI_MODEL", "gemini-1.5-flash")
                model_obj = genai.GenerativeModel(gemini_model)  # type: ignore
                # Emulate system prompt by prefixing
                resp = model_obj.generate_content([system_prompt, prompt])
                text = getattr(resp, "text", None)
                if not text and hasattr(resp, "candidates"):
                    # Fallback extraction
                    for c in resp.candidates:  # type: ignore
                        parts = getattr(getattr(c, "content", None), "parts", None)
                        if parts:
                            return str(parts[0].text).strip()
                return (text or "").strip()
            except Exception:
                pass
        if provider == "gemini":
            return (
                "[AI offline] Set GEMINI_API_KEY or set AI_PROVIDER=openai with OPENAI_API_KEY.\n\n"
                f"Echoing: {prompt[:500]}"
            )

    # Final offline fallback
    return (
        "[AI offline] Set OPENAI_API_KEY or GEMINI_API_KEY.\n\n"
        f"Echoing: {prompt[:500]}"
    )


def build_ppt_from_outline(title: str, slides: List[dict]) -> Presentation:
    prs = Presentation()
    # Title slide
    title_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_layout)
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by SmartStudy AI"

    bullet_layout = prs.slide_layouts[1]
    for item in slides:
        s = prs.slides.add_slide(bullet_layout)
        s.shapes.title.text = item.get("title", "")
        body = s.shapes.placeholders[1].text_frame
        body.clear()
        bullets = item.get("bullets", [])
        for idx, bullet in enumerate(bullets):
            if idx == 0:
                body.text = bullet
            else:
                p = body.add_paragraph()
                p.text = bullet
                p.level = 1
        for p in body.paragraphs:
            for run in p.runs:
                run.font.size = Pt(20)
    return prs


def generate_ppt_outline(topic: str, num_slides: int = 8, bullets_per_slide: int = 4, role_hint: str = "student") -> List[dict]:
    prompt = (
        "Create an outline for a PowerPoint about '" + topic + "'.\n"
        f"- {num_slides} slides (excluding title).\n"
        f"- {bullets_per_slide} concise bullets per slide.\n"
        f"- Audience: {role_hint}.\n"
        "Return JSON with an array named slides: [{title: str, bullets: [str, ...]}]."
    )
    text = get_llm_response(prompt, role_hint=role_hint)

    # Try to parse JSON, fall back to heuristic
    import json
    slides: List[dict] = []
    try:
        data = json.loads(text)
        slides = data.get("slides", [])
    except Exception:
        # Heuristic parse: split lines by dashes
        lines = [ln.strip(" -\t") for ln in text.splitlines() if ln.strip()]
        cur_title: Optional[str] = None
        cur_bullets: List[str] = []
        for ln in lines:
            if ln.endswith(":") and len(cur_bullets) == 0 and cur_title is None:
                cur_title = ln[:-1]
            elif ln.startswith("-") or ln.startswith("*"):
                cur_bullets.append(ln.lstrip("-* "))
            elif cur_title and cur_bullets:
                slides.append({"title": cur_title, "bullets": cur_bullets[:bullets_per_slide]})
                cur_title, cur_bullets = ln, []
        if cur_title and cur_bullets:
            slides.append({"title": cur_title, "bullets": cur_bullets[:bullets_per_slide]})

    # Clamp to requested lengths
    slides = slides[:num_slides]
    for s in slides:
        s["bullets"] = (s.get("bullets") or [])[:bullets_per_slide]
    if not slides:
        # Minimal fallback
        slides = [{"title": f"About {topic}", "bullets": ["Overview", "Key points", "Examples", "Summary"]}]
    return slides


def generate_ppt(topic: str, role_hint: str = "student", num_slides: int = 8, bullets_per_slide: int = 4) -> Presentation:
    outline = generate_ppt_outline(topic, num_slides=num_slides, bullets_per_slide=bullets_per_slide, role_hint=role_hint)
    prs = build_ppt_from_outline(topic, outline)
    return prs


