# Generated by Django 5.2.5 on 2025-10-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyPortal', '0003_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='score',
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='uploaded_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
