# Generated by Django 5.2.6 on 2025-09-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyPortal', '0003_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
