# Generated by Django 5.2.5 on 2025-10-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyPortal', '0004_delete_mymodel_remove_assignment_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='student_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
