# Generated by Django 5.2.7 on 2025-10-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyPortal', '0005_studentprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProgress',
        ),
        migrations.AddField(
            model_name='progress',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='student_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
    ]
