# Generated by Django 5.2.5 on 2025-10-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyPortal', '0006_note_file_note_uploaded_at_resource_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
    ]
