# Generated by Django 5.2.5 on 2025-10-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyPortal', '0007_book_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='student_name',
        ),
        migrations.AlterField(
            model_name='progress',
            name='progress_percent',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='StudyPortal.course')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['name'],
            },
        ),
    ]
