# Generated by Django 5.2.5 on 2025-10-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyPortal', '0009_assignment_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='file',
            new_name='assignment_file',
        ),
        migrations.AddField(
            model_name='assignment',
            name='submit_assignment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
    ]
