# Generated by Django 5.2.5 on 2025-10-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyPortal', '0008_rename_file_assignment_assignment_file_and_more'),
        ('StudyPortal', '0010_rename_file_assignment_assignment_file_and_more'),
    ]

    operations = [
    ]
