# Generated by Django 5.2.5 on 2025-10-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyPortal', '0011_studentprofile_assignment_sudents_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='sudents',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
